_extends: .github:.github/release-drafter.yml
name-template: '3.$MINOR.$PATCH'
tag-template: 'plexus-xml-3.$MINOR.$PATCH'
version-template: '3.$MINOR.$PATCH'
commitish: '3.x'
filter-by-commitish: true
